export const data = [
	{
		id: 1,
		src: 'images/prod_cart1.jpg',
		title: 'Nice t-short',
		description: 'The best of the best very nice t-short',
		price: '$53.00',
	},
	{
		id: 2,
		src: 'images/prod_cart2.jpg',
		title: 'Nice t-short',
		description: 'The best of the best very nice t-short',
		price: '$58.00',
	},
	{
		id: 3,
		src: 'images/prod_cart3.jpg',
		title: 'Nice t-short',
		description: 'The best of the best very nice t-short',
		price: '$12.00',
	},
	{
		id: 4,
		src: 'images/prod_cart4.jpg',
		title: 'Nice t-short',
		description: 'The best of the best very nice t-short',
		price: '$72.00',
	},
	{
		id: 5,
		src: 'images/prod_cart5.jpg',
		title: 'Nice t-short',
		description: 'The best of the best very nice t-short',
		price: '$56.00',
	},
	{
		id: 6,
		src: 'images/prod_cart6.jpg',
		title: 'Nice t-short',
		description: 'The best of the best very nice t-short',
		price: '$52.00',
	},
	{
		id: 7,
		src: 'images/prod_cart7.jpg',
		title: 'Wow t-short',
		description: 'The best of the best very nice t-short',
		price: '$32.00',
	},
	{
		id: 8,
		src: 'images/prod_cart8.jpg',
		title: 'Nice t-short',
		description: 'The best of the best very nice t-short',
		price: '$48.00',
	},
];
